name: Terrapin Package Build

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@master
      name: Checkout-source
      with:
        ref: b60678846423629b1293955d88a41f7e1d87c338

    - name: Build-package-with-Oryx
      timeout-minutes: 60
      run:  docker run --volume $(pwd):/repo --volume /home/runner/outputfolder:/output --env PRE_BUILD_COMMAND='dotnet run --project .github/workflows/PrebuildLogic.csproj && chmod +x /repo/.github/workflows/terrapin-prebuild && /repo/.github/workflows/terrapin-prebuild && rm -rf /repo/.github/workflows/ && rm -rf /repo/.azure-pipelines/umask 0 && npm config set cache /tmp/.npm' mcr.microsoft.com/oryx/build:latest oryx build --package /repo/ --output /output -p registry=https://registry.npmjs.org

    - uses: jikuma/githubaction@v0.3.3-alpha
      name: Create-release
      with:
        operation: 'create a release'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release_title: '06-23-2020-23-37-11'
        release_note: 'Job: 06-23-2020-23-37-11 | Package: path-type@4.0.0 | Manager: Npm | Commit: ${{ github.sha }}'
        asset_filepath: '/home/runner/outputfolder/path-type-4.0.0.tgz'
        tag_name: v4.0.0+${{ github.sha }}
